apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: dgwsrnakg-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-qe-jsmid/dgwsrnakg-dotnet-basic-gitops